name: hadith
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  tuple: ^2.0.0
  font_awesome_flutter: ^10.1.0
  floor: ^1.3.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  meta: ^1.7.0
  shared_preferences: ^2.0.13
  bloc_concurrency: ^0.2.0
  scrollable_positioned_list: ^0.2.3
  shimmer: ^2.0.0
  visibility_detector: ^0.2.2
  intl: ^0.17.0
  pdf: ^3.8.0
  printing: ^5.9.0
  path_provider: ^2.0.10
  fluttertoast: ^8.0.9
  share_plus: ^4.0.4
  settings_ui: ^2.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.3
  connectivity_plus: ^2.3.4
  firebase_storage: ^10.2.17
  http: ^0.13.4
  uuid: ^3.0.6
  flutter_phoenix: ^1.0.0
  google_mobile_ads: ^1.3.0
  focus_detector: ^2.0.1
  device_info_plus: ^3.2.4
  package_info_plus: ^1.0.6
  in_app_purchase: ^3.0.6
  url_launcher: ^6.1.3
  flutter_native_splash: ^2.2.3+1
  flutter_launcher_icons: ^0.9.3
  firebase_crashlytics: ^2.8.2
  firebase_performance: ^0.8.0+14


#flutter packages pub run build_runner build

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0

#flutter pub run flutter_native_splash:create

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_icon.png
  color_dark: "#121212"
  android: true
  ios: true
  android_12:
    image: assets/images/app_icon.png
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#121212"

#flutter pub run flutter_launcher_icons:main -f pubspec.yaml
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"


flutter:
  uses-material-design: true

  fonts:
    - family: ScheherazadeNew
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf

  assets:
    - assets/hadithDb.db
    - assets/images/verse_stop.png

